services:
    discord-message-cleaner:
        container_name: 'DiscordMessageCleaner'
        environment:
          - 'TOKEN=<your_discord_bot_token>'
          - 'CHANNEL_ID=<your_discord_channel_id>'
        image: 'rix1337/docker-discord-message-cleaner:latest'
